---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install Node.js
  become: true
  ansible.builtin.shell: |
    curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash -
    apt install nodejs
    apt update -y

- name: Install npm packages
  npm:
    name: [pm2]
    global: yes
    

