---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install Node.js
  ansible.builtin.apt:
    repository: https://deb.nodesource.com/setup_17.x
    state: present
    update_cache: yes

- name: Install npm packages
  ansible.builtin.npm:
    name: [pm2]
    global: yes
    

