---
- name: Extract back-end archive
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src: yes 

- name: Install dependencies
  ansible.builtin.npm:
    path: /home/ubuntu/  

- name: Manage app with PM2
  ansible.builtin.pm2:
    name: default
    state: stopped

- name: Start app with PM2
  ansible.builtin.pm2:
    name: npm
    script: start