---
- name: Extract back-end tar
  ansible.builtin.unarchive:
        src: ~/project/artifact.tar.gz
        dest: /home/ubuntu/
        remote_src: yes
- name: Start App
  ansible.builtin.shell: |
    cd /home/ubuntu/
    npm install
    pm2 stop default
    pm2 start npm -- start